/**
 * Autogenerated by Postman CLI (postman mock generate)
 */
const http = require('http');
const PORT = process.env.PORT || 5004;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint GET /health
  if (req.method === 'GET' && pathname === '/health') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"status":"ok","service":"inventory-service"}));
  }

  // @endpoint GET /api/inventory
  if (req.method === 'GET' && pathname === '/api/inventory') {
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify([{"productId":"p1","sku":"SKU-P1-HEADPHN","quantityAvailable":48,"warehouse":"US-EAST-1","lastRestockedAt":"2026-09-30T08:00:00.000Z"},{"productId":"p2","sku":"SKU-P2-SMARTWCH","quantityAvailable":2,"warehouse":"US-WEST-1","lastRestockedAt":"2026-09-15T08:00:00.000Z"}]));
  }

  // @endpoint GET /api/inventory/:productId
  if (req.method === 'GET' && /^\/api\/inventory\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "No inventory record exists for this productId." — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"Inventory record not found"}));
    }

    // "The inventory record for the given product." — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"productId":"p1","sku":"SKU-P1-HEADPHN","quantityAvailable":48,"warehouse":"US-EAST-1","lastRestockedAt":"2026-09-30T08:00:00.000Z"}));
  }

  // @endpoint PUT /api/inventory/:productId
  if (req.method === 'PUT' && /^\/api\/inventory\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "quantityAvailable is missing or not a number >= 0." — when x-mock-response-code: 400
    if (requestedStatusCode === '400') {
      res.writeHead(400, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"quantityAvailable must be a number >= 0"}));
    }

    // "The updated inventory record." — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"productId":"p1","sku":"SKU-P1-HEADPHN","quantityAvailable":25,"warehouse":"US-EAST-1","lastRestockedAt":"2026-09-30T08:00:00.000Z"}));
  }

  // @endpoint POST /api/inventory/:productId/reserve
  if (req.method === 'POST' && /^\/api\/inventory\/([^/]+)\/reserve$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "quantity is invalid, or exceeds quantityAvailable." — when x-mock-response-code: 400
    if (requestedStatusCode === '400') {
      res.writeHead(400, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"Insufficient stock"}));
    }

    // "No inventory record exists for this productId." — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"error":"Inventory record not found"}));
    }

    // "The updated inventory record after the reservation." — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"productId":"p1","sku":"SKU-P1-HEADPHN","quantityAvailable":47,"warehouse":"US-EAST-1","lastRestockedAt":"2026-09-30T08:00:00.000Z"}));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
